# Generated by Django 3.2.7 on 2021-10-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_blogs_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
